# Generated by Django 5.2.4 on 2025-08-04 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_transactioncategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.transactioncategory'),
        ),
        migrations.AlterField(
            model_name='transactioncategory',
            name='name',
            field=models.CharField(default=10, max_length=20),
        ),
    ]
